# Generated by Django 4.1 on 2024-02-28 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=100)),
                ('crime_name_second', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_start_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('crime_end_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('crime_place', models.CharField(max_length=100)),
                ('crime_fact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VictimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsapp.crimemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honseki', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsapp.crimemodel')),
            ],
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsapp.genremodel'),
        ),
    ]
