# Generated by Django 4.1 on 2024-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimemodel',
            name='crime_end_datetime',
        ),
        migrations.RemoveField(
            model_name='crimemodel',
            name='crime_start_datetime',
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='crime_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='crime_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='crime_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='crime_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
